version: '2'

# 251214.1
services:

  app:
    image: docker.io/arhar/ezrfs:251214.2
    ports:
      - "8081:8081"
    expose:
      - "8081"
    volumes:
      - /opt/ezlfs/.storage:/work/.cache/ezlfs/.storage
